#!/usr/bin/env bash
set -euo pipefail

# gen-clangd.sh — Generate a .clangd that mirrors your compiler's system include paths.
#
# Presets:
#   --toolchain host            -> uses $CXX or g++
#   --toolchain clang           -> clang++
#   --toolchain arm-none-eabi   -> arm-none-eabi-g++
#   --toolchain mingw           -> x86_64-w64-mingw32-g++
#
# Options:
#   --compiler <CXX>            -> explicit compiler (overrides --toolchain)
#   --std <c++NN>               -> default c++20
#   --out <file>                -> output file (default .clangd)
#
# ARM-specific extras (only relevant for arm-none-eabi):
#   --root <path>               -> xPack root (default: $HOME/xpack-arm-none-eabi-gcc-14.2.1-1.1)
#   --cpu <cortex-mX>           -> CPU (default: cortex-m0plus)
#   --float-abi <soft|hard>     -> float ABI (default: soft)
#
# Examples:
#   ./gen-clangd.sh --toolchain host
#   ./gen-clangd.sh --toolchain arm-none-eabi --cpu cortex-m4 --std c++20
#   ./gen-clangd.sh --compiler clang++ --std c++23 --out .clangd.clang

toolchain="host"
compiler="${CXX:-g++}"
std="c++20"
out=".clangd"
user_set_compiler=0

# ARM-specific defaults
XPACK_ROOT="${XPACK_ROOT:-$HOME/xpack-arm-none-eabi-gcc-14.2.1-1.1}"
CPU="cortex-m0plus"
FLOAT_ABI="soft"

print_help() {
  sed -n '1,120p' "$0"
}

# ---- parse args -------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --toolchain) toolchain="$2"; shift 2 ;;
    --compiler)  compiler="$2"; user_set_compiler=1; shift 2 ;;
    --std)       std="$2"; shift 2 ;;
    --out)       out="$2"; shift 2 ;;
    --root)      XPACK_ROOT="$2"; shift 2 ;;
    --cpu)       CPU="$2"; shift 2 ;;
    --float-abi) FLOAT_ABI="$2"; shift 2 ;;
    -h|--help)   print_help; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

# ---- resolve compiler from preset unless user overrode ----------------------
if [[ $user_set_compiler -eq 0 ]]; then
  case "$toolchain" in
    host)             compiler="${CXX:-g++}" ;;
    clang)            compiler="clang++" ;;
    arm-none-eabi)    compiler="arm-none-eabi-g++" ;;
    mingw)            compiler="x86_64-w64-mingw32-g++" ;;
    *)
      echo "error: unknown --toolchain '$toolchain' (valid: host|clang|arm-none-eabi|mingw)" >&2
      exit 1
      ;;
  esac
fi

command -v "$compiler" >/dev/null 2>&1 || { echo "error: compiler '$compiler' not found in PATH" >&2; exit 1; }

echo ">> Toolchain: $toolchain"
echo ">> Compiler : $compiler"
echo ">> Std      : $std"
echo ">> Outfile  : $out"

# ---- query compiler for system include search list --------------------------
VERBOSE_OUT="$("$compiler" -E -x c++ - -v </dev/null 2>&1 || true)"

mapfile -t INC_PATHS < <(printf "%s\n" "$VERBOSE_OUT" \
  | awk '
      /^#include <\.\.\.> search starts here:/ { capture=1; next }
      /^End of search list\./ { capture=0 }
      capture { gsub(/^[[:space:]]+/, "", $0); print $0 }
    ' \
  | sed 's/ (framework directory.*)//'
)

# De-dup
uniq_paths=()
seen="|"
for p in "${INC_PATHS[@]}"; do
  [[ -d "$p" ]] || continue
  if [[ "$seen" != *"|$p|"* ]]; then
    uniq_paths+=("$p")
    seen+="$p|"
  fi
done

# ARM fallback guess (only if arm-none-eabi)
if [[ "$toolchain" == "arm-none-eabi" ]]; then
  guess="$XPACK_ROOT/arm-none-eabi/include/c++"
  if [[ -d "$guess" ]]; then
    ver_dir="$(ls -1 "$guess" | sort -V | tail -n1 || true)"
    if [[ -n "$ver_dir" && -d "$guess/$ver_dir" ]]; then
      uniq_paths+=("$guess/$ver_dir" "$guess/$ver_dir/arm-none-eabi")
    fi
  fi
fi

# Build YAML includes
yaml_includes=()
for p in "${uniq_paths[@]}"; do
  yaml_includes+=("\"-isystem\" \"$p\"")
done

# Backup if overwriting
if [[ "$out" == ".clangd" && -f .clangd ]]; then
  cp -f .clangd .clangd.bak
  echo ">> Backed up existing .clangd -> .clangd.bak"
fi

# ---- write the .clangd ------------------------------------------------------
{
  echo "# Auto-generated by gen-clangd on $(date -Iseconds)"
  echo "# Toolchain: $toolchain"
  echo "# Compiler : $compiler"
  echo "CompileFlags:"
  echo "  Add: ["
  printf "    \"-std=%s\",\n" "$std"

  if [[ "$toolchain" == "arm-none-eabi" ]]; then
    printf "    \"-target\", \"arm-none-eabi\",\n"
    printf "    \"-mcpu=%s\",\n" "$CPU"
    printf "    \"-mfloat-abi=%s\",\n" "$FLOAT_ABI"
    printf "    \"-mthumb\",\n"
    printf "    \"-nostdinc++\",\n"
  fi

  for p in "${uniq_paths[@]}"; do
    printf "    \"-isystem\", \"%s\",\n" "$p"
  done
  echo "  ]"
  echo ""
} > "$out"

echo ">> Wrote $out with ${#uniq_paths[@]} include dirs"

